### PR TITLE
packed everything in a docker image

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by bernhard-42** [comment]
Thanks for creating the docker image - it was on my todo list and is done now ;-)

I think I added dataclasses yesterday, so I might adapt the Dockerfile to include it

**Comment by bernhard-42** [comment]
@ilya-epifanov As expected, I had to add `dataclasses`

Additionally I had to add 
```bash
docker build -t bernhard-42/jupyter-cadquery .
```

to the README

**Comment by ilya-epifanov** [comment]
@bernhard-42 Why don't you set up an automatic build in docker hub? This way users won't need to build anything.

**Comment by bernhard-42** [comment]
Agreed. Now that I am pretty much done with this version, I will publish it to pypi and docker hub and adapt the docs accordingly.

**Comment by ilya-epifanov** [comment]
Thanks a lot!

**Comment by westurner** [comment]
repo2docker is another way to create a Dockerfile / Docker image (that works with https://mybinder.org/)

It'll build from `environment.yml` (which can contain conda packages and pip packages)
https://repo2docker.readthedocs.io/en/latest/howto/export_environment.html

repo2docker will build with the `environment.yml` if it's found before a `Dockerfile` *instead of* the Dockerfile:
https://repo2docker.readthedocs.io/en/latest/config_files.html#config-files

repo2docker can then run a `postBuild` script (e.g. containing the necessary `jupyterlab-extension` commands)

**Comment by westurner** [comment]
See https://github.com/bernhard-42/jupyter-cadquery/issues/2 regarding pinning versions in environment.yml (and creating tagged docker images)

**Pull request merged**
